version: '3.9'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
      - APP_NAME=seat-scheduler
      - PORT=80
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/seat-scheduler-test
      - REDIS_URI=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3-alpine3.19
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
