services:
  app:
    build: .
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - APP_NAME=seat-scheduler
      - PORT=3000
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/seat_scheduler_test
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3-alpine3.20
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seat_scheduler_test
    volumes:
      - pg-data:/var/lib/postgresql/data

  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - '8080:80'

volumes:
  pg-data:
