version: '3.9'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
      - APP_NAME=seat-scheduler
      - PORT=80
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/seat_scheduler_test
      - REDIS_URI=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seat_scheduler_test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
